### ISSUE TITLE
Mac OSX 10.11.4  Sublime 2 下从unicode 转成中文没有起作用

### ISSUE THREAD

**Issue by nevercry** [iahu/unicode-escape#2]
我把快捷键设置倒过来也没有用。
控制台的报错信息：
`Traceback (most recent call last):
  File "./sublime_plugin.py", line 362, in run_
  File "./escape.py", line 19, in run
TypeError: str() takes at most 1 argument (2 given)`

**Comment by nevercry** [comment]
`self.view.replace(edit, sel, bytes( t, 'utf-8' ).decode('unicode_escape') );`
我把这里改了下，去掉了bytes里面的`'utf-8'`参数就好了。
`self.view.replace(edit, sel, bytes( t ).decode('unicode_escape') );`
